In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.0000e+00, -5.5124e+13],
        [-1.0845e-19,  2.0660e+22,  4.5779e-41],
        [ 4.5833e+30,  4.2039e-45,  7.7782e+31],
        [ 0.0000e+00,  2.0690e+22,  4.5779e-41],
        [ 2.3690e+22,  4.5779e-41,  2.3690e+22]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7510, 0.0107, 0.5519],
        [0.4812, 0.1636, 0.5649],
        [0.1281, 0.2669, 0.1251],
        [0.2343, 0.7389, 0.4817],
        [0.4000, 0.0721, 0.9342]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.6122, -0.3111,  0.3369],
        [-0.2758,  1.4560, -0.5809],
        [ 0.2267,  1.3985,  0.1982],
        [ 0.4470, -0.7771, -0.0093],
        [ 1.2226, -0.6318,  0.7601]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.7676, -0.2753,  1.1212],
        [ 0.4797,  2.2810,  0.2115],
        [ 0.5569,  1.5835,  0.2414],
        [ 0.6978,  0.1038,  0.6077],
        [ 1.3690, -0.0825,  1.0481]])


In [9]:
print(torch.add(x, y))

tensor([[-0.7676, -0.2753,  1.1212],
        [ 0.4797,  2.2810,  0.2115],
        [ 0.5569,  1.5835,  0.2414],
        [ 0.6978,  0.1038,  0.6077],
        [ 1.3690, -0.0825,  1.0481]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.7676, -0.2753,  1.1212],
        [ 0.4797,  2.2810,  0.2115],
        [ 0.5569,  1.5835,  0.2414],
        [ 0.6978,  0.1038,  0.6077],
        [ 1.3690, -0.0825,  1.0481]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.7676, -0.2753,  1.1212],
        [ 0.4797,  2.2810,  0.2115],
        [ 0.5569,  1.5835,  0.2414],
        [ 0.6978,  0.1038,  0.6077],
        [ 1.3690, -0.0825,  1.0481]])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())
print(x[0])

tensor([0.9281])
0.9280689358711243
tensor(0.9281)


In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[ 3.  3.  3.  3.  3.]


In [20]:
b = b + 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 3.  3.  3.  3.  3.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!